# -*- coding: utf-8 -*-
"""Sales_Tax_Calculation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hv_Pp4vEkA3P1wXWEhc_y9KYWRgvjjy3
"""

import pandas as pd
import csv

Product_Catalog_DF = pd.read_csv("ProductCatalog.csv")
Sales_Tax_DF = pd.read_csv("SalesTax.csv")

with open("result.csv", "w", newline="") as csvFileObject:
    thewritter = csv.writer(csvFileObject)

    thewritter.writerow(["Product-Name", "Product-CostPrice", "Product-SalesTax", "Product-SalesTaxAmount", "Product-FinalPrice", "Country"])

    sales_tax_df_index = 0

    while sales_tax_df_index < len(Sales_Tax_DF):
        product_catalog_df_index = 0
        while product_catalog_df_index < len(Product_Catalog_DF):
            Tax_Price = (float(Sales_Tax_DF['SalseTaxInPercent'][sales_tax_df_index])* float(Product_Catalog_DF['ProductCost'][product_catalog_df_index]))/100
            Sales_Price = float(Product_Catalog_DF['ProductCost'][product_catalog_df_index])+Tax_Price
    
            thewritter.writerow([Product_Catalog_DF['ProductName'][product_catalog_df_index], Product_Catalog_DF['ProductCost'][product_catalog_df_index], Sales_Tax_DF['SalseTaxInPercent'][sales_tax_df_index], Tax_Price, Sales_Price, Sales_Tax_DF['Country'][sales_tax_df_index]])
            product_catalog_df_index+=1
        sales_tax_df_index+=1